language: python
os: linux
dist: xenial
jobs:
  fast_finish: true
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: nightly
  allow_failures:
    - python: nightly
# command to run tests
install: python setup.py develop
script: python setup.py test

